version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=${API_KEY}  # مقداردهی از فایل .env
      - CACHE_TTL=300
    depends_on:
      - redis
      - prometheus
    networks:
      - app-network

  redis:
    image: ghcr.io/aut-cloud-computing-fall-2024/redis:latest
    volumes:
      - redis-data:/data
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
