apiVersion: v1
kind: Service
metadata:
  name: nextjs-service
  namespace: demo-ns
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: demo-ns
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: demo-ns
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
  clusterIP: None
