name: Docker Image CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag my-image-name:latest
          docker tag my-image-name:latest ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

      - name: Logout from Docker Hub
        run: docker logout
